version: '3.5'

services: 
    notification-service:
        image: sneyd321/notification-service
        ports: 
            - 8093:8093
        volumes: 
            - ./:/usr/src/app
        restart: on-failure

   
   
          

 
    